[package]
name = "guessing_game"
version = "0.1.0"
authors = ["shamisonn <unknown0incident@gmail.com>"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
